// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBmPBaP4pl3aeUWGBe0BGrHvi40S_kwg',
    appId: '1:209449932007:web:b970df9fbc9c640c22fe42',
    messagingSenderId: '209449932007',
    projectId: 'feedback-form-623f0',
    authDomain: 'feedback-form-623f0.firebaseapp.com',
    databaseURL: 'https://feedback-form-623f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedback-form-623f0.firebasestorage.app',
    measurementId: 'G-DJV7GFKY71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn5lCenSaRYd8_YVB78FtBT4qVedLhIzk',
    appId: '1:209449932007:android:d94e4655eb9497f522fe42',
    messagingSenderId: '209449932007',
    projectId: 'feedback-form-623f0',
    databaseURL: 'https://feedback-form-623f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedback-form-623f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvV7trYqc6HiEoBU4pLR-52m_S0Dg_NA',
    appId: '1:209449932007:ios:eac819bd27d8cda922fe42',
    messagingSenderId: '209449932007',
    projectId: 'feedback-form-623f0',
    databaseURL: 'https://feedback-form-623f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedback-form-623f0.firebasestorage.app',
    iosBundleId: 'com.example.feedbackForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvV7trYqc6HiEoBU4pLR-52m_S0Dg_NA',
    appId: '1:209449932007:ios:eac819bd27d8cda922fe42',
    messagingSenderId: '209449932007',
    projectId: 'feedback-form-623f0',
    databaseURL: 'https://feedback-form-623f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedback-form-623f0.firebasestorage.app',
    iosBundleId: 'com.example.feedbackForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmBmPBaP4pl3aeUWGBe0BGrHvi40S_kwg',
    appId: '1:209449932007:web:426a593bf90a91b922fe42',
    messagingSenderId: '209449932007',
    projectId: 'feedback-form-623f0',
    authDomain: 'feedback-form-623f0.firebaseapp.com',
    databaseURL: 'https://feedback-form-623f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'feedback-form-623f0.firebasestorage.app',
    measurementId: 'G-ZX1HTNYY4Z',
  );
}
